"""add units and category_units

Revision ID: 3d4275ecfd3e
Revises: b6945e8c7872
Create Date: 2026-03-02 17:04:43.580852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4275ecfd3e'
down_revision: Union[str, None] = 'b6945e8c7872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('WEIGHT', 'VOLUME', 'COUNT', name='unit_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_unit', sa.String(length=50), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_units_name'),
    sa.UniqueConstraint('short_code', name='uq_units_short_code')
    )
    op.create_index(op.f('ix_units_created_at'), 'units', ['created_at'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_index(op.f('ix_units_short_code'), 'units', ['short_code'], unique=False)
    op.create_index('ix_units_type', 'units', ['type'], unique=False)
    op.create_index(op.f('ix_units_updated_at'), 'units', ['updated_at'], unique=False)
    op.create_table('category_units',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'unit_id', name='uq_category_units_category_unit')
    )
    op.create_index('ix_category_units_category_id', 'category_units', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_units_created_at'), 'category_units', ['created_at'], unique=False)
    op.create_index('ix_category_units_unit_id', 'category_units', ['unit_id'], unique=False)
    op.create_index(op.f('ix_category_units_updated_at'), 'category_units', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_units_updated_at'), table_name='category_units')
    op.drop_index('ix_category_units_unit_id', table_name='category_units')
    op.drop_index(op.f('ix_category_units_created_at'), table_name='category_units')
    op.drop_index('ix_category_units_category_id', table_name='category_units')
    op.drop_table('category_units')
    op.drop_index(op.f('ix_units_updated_at'), table_name='units')
    op.drop_index('ix_units_type', table_name='units')
    op.drop_index(op.f('ix_units_short_code'), table_name='units')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_created_at'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
