"""add parent_id to categories with new fields

Revision ID: 96153f250b24
Revises: 72c7ec9b5ea8
Create Date: 2026-03-02 16:21:29.846737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96153f250b24'
down_revision: Union[str, None] = '72c7ec9b5ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index('ix_categories_is_active_name', 'categories', ['is_active', 'name'], unique=False)
    op.create_index('ix_categories_name_trgm', 'categories', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_name_trgm', table_name='categories', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_categories_is_active_name', table_name='categories')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
